config/routes.rb
SouthTexasJazzFoundation::Application.routes.draw do
  resources :donor_receipts, only: [:index] do
    member do
      post 'resend_receipt'
    end
  end
  resources :donors, only: [:index]
  resources :press_releases
  resources :donations
  post 'donations/hook', to: 'donations#hook'
  resources :biographies
  get '/band_members' => 'biographies#index', :as => 'band_members'
  get '/band_members/:id' => 'biographies#show', :as => 'band_member'

  devise_for :members

  root to: 'home#index'
  get 'home/index'

end

app/models/biography.rb
class Biography < ActiveRecord::Base
  attr_accessible :biography, :first_name, :instrument, :last_name, :section

  scope :conductors, -> { where(section: 'conductor').order('last_name') }
  scope :saxes,      -> { where(section: 'sax').order('last_name')       }
  scope :bones,      -> { where(section: 'bone').order('last_name')      }
  scope :trumpets,   -> { where(section: 'trumpet').order('last_name')   }
  scope :rhythm,     -> { where(section: 'rhythm').order('last_name')    }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/biographies_controller.rb
class BiographiesController < ApplicationController
  before_filter :authenticate_member!, except: [:index, :show]

  # GET /biographies
  # GET /biographies.json
  def index
    @presenter = BioPresenter.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @biographies }
    end
  end

  # GET /biographies/1
  # GET /biographies/1.json
  def show
    @biography = Biography.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @biography }
    end
  end

  # GET /biographies/new
  # GET /biographies/new.json
  def new
    @biography = Biography.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @biography }
    end
  end

  # GET /biographies/1/edit
  def edit
    @biography = Biography.find(params[:id])
  end

  # POST /biographies
  # POST /biographies.json
  def create
    @biography = Biography.new(params[:biography])

    respond_to do |format|
      if @biography.save
        format.html { redirect_to @biography, notice: 'Biography was successfully created.' }
        format.json { render json: @biography, status: :created, location: @biography }
      else
        format.html { render action: 'new' }
        format.json { render json: @biography.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /biographies/1
  # PUT /biographies/1.json
  def update
    @biography = Biography.find(params[:id])

    respond_to do |format|
      if @biography.update_attributes(params[:biography])
        format.html { redirect_to @biography, notice: 'Biography was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @biography.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /biographies/1
  # DELETE /biographies/1.json
  def destroy
    @biography = Biography.find(params[:id])
    @biography.destroy

    respond_to do |format|
      format.html { redirect_to biographies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/biographies_helper.rb
module BiographiesHelper
end

app/views/biographies/_form.html.haml
= form_for @biography do |f|
  - if @biography.errors.any?
    #error_explanation
      %h2= "#{pluralize(@biography.errors.count, "error")} prohibited this biography from being saved:"
      %ul
        - @biography.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :section
    = f.text_field :section
  .field
    = f.label :instrument
    = f.text_field :instrument
  .field
    = f.label :biography
    = f.text_area :biography
  .actions
    = f.submit 'Save'

app/views/biographies/edit.html.haml
%h1 Editing biography

= render 'form'

= link_to 'Show', @biography
\|
= link_to 'Back', biographies_path

app/views/biographies/index.html.haml
- if member_signed_in?
  .row
    = link_to 'New Member Bio', new_biography_path
- @presenter.band.each do |header, section|
  .row
    = header
  .row
    - section.each do |person|
      .span2= link_to person.full_name, band_member_path(person)
      - if member_signed_in?
        .row
          (
          = link_to 'Edit', edit_biography_path(person)
          = link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' }
          )
    .row
      %hr

app/views/biographies/new.html.haml
%h1 New biography

= render 'form'

= link_to 'Back', biographies_path

app/views/biographies/show.html.haml
%p.notice= notice

.row
  .span2
    %b Name:
  .span4
    = @biography.first_name + ' ' + @biography.last_name

.row
  .span2
    %b Instrument:
  .span4
    = @biography.instrument
  
.row
  .span2
    %b Biography:
  .span8= raw @biography.biography

- if member_signed_in?
  = link_to 'Edit', edit_biography_path(@biography)
  \|
  = link_to 'Back', biographies_path