config/routes.rb
SouthTexasJazzFoundation::Application.routes.draw do
  resources :donor_receipts, only: [:index] do
    member do
      post 'resend_receipt'
    end
  end
  resources :donors, only: [:index]
  resources :press_releases
  resources :donations
  post 'donations/hook', to: 'donations#hook'
  resources :biographies
  get '/band_members' => 'biographies#index', :as => 'band_members'
  get '/band_members/:id' => 'biographies#show', :as => 'band_member'

  devise_for :members

  root to: 'home#index'
  get 'home/index'

end

app/controllers/donor_receipts_controller.rb
class DonorReceiptsController < ApplicationController
  before_filter :authenticate_member!

  def index
    @donors = Donation.all
  end

  def resend_receipt
    donation = Donation.find(params[:id])
    send_receipt(donation.email, donation.token)
    redirect_to donor_receipts_path, notice: 'Receipt Sent'
  end
end

app/helpers/donor_receipts_helper.rb
module DonorReceiptsHelper
end

app/views/donor_receipts/index.html.haml
%table.table.table-striped
  %tr
    %th
      Name
    %th
      Email
    %th
      Donation Amount
    %th
      Created
    %th
      Stripe Info
    %th
  - @donors.each do |donor|
    %tr
      %td
        = donor.name
      %td
        = mail_to donor.email
      %td
        $
        = donor.amount
      %td
        = time_ago_in_words donor.created_at
      %td
        = link_to 'Get Stripe Info', "https://manage.stripe.com/payments/#{donor.token}"
      %td
        = button_to 'Resend Receipt', resend_receipt_donor_receipt_path(donor), class: 'btn'