config/routes.rb
SouthTexasJazzFoundation::Application.routes.draw do
  resources :donor_receipts, only: [:index] do
    member do
      post 'resend_receipt'
    end
  end
  resources :donors, only: [:index]
  resources :press_releases
  resources :donations
  post 'donations/hook', to: 'donations#hook'
  resources :biographies
  get '/band_members' => 'biographies#index', :as => 'band_members'
  get '/band_members/:id' => 'biographies#show', :as => 'band_member'

  devise_for :members

  root to: 'home#index'
  get 'home/index'

end

app/views/layouts/_google.html.haml
:javascript
  var _gaq=[['_setAccount','UA-36673314-1'],['_trackPageview']];
  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
  g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
  s.parentNode.insertBefore(g,s)}(document,'script'));

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title South Texas Jazz Foundation
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "https://js.stripe.com/v2/", "application"
    = javascript_include_tag "application"
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}
    = stylesheet_link_tag "/css/focus.css"
    = stylesheet_link_tag "/css/focus-responsive.css"
    = stylesheet_link_tag "/css/pages/homepage.css"
    = stylesheet_link_tag "/css/components/plans.css"
    / Le HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    = render 'layouts/google'
    = content_for :head
    = tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY
    = csrf_meta_tags
  %body
    #wrapper.clearfix
      #header
        %h1
          = link_to "South Texas Jazz Foundation", root_path
      .row
        #nav.clearfix
          .container
            %ul#main-nav
              = nav_link 'Home', root_path, { :class => 'link' }, {:wrapper => 'li', :wrapper_class => '', :selected_class => 'active'}
              = nav_link 'Photos', photo_albums_path, { :class => 'link' }, {:wrapper => 'li', :wrapper_class => '', :selected_class => 'active', :url_segment => 1}
              = nav_link 'Band Members', band_members_path, { :class => 'link' }, {:wrapper => 'li', :wrapper_class => '', :selected_class => 'active', :url_segment => 1}
              = nav_link 'Press Releases', press_releases_path, { :class => 'link' }, {:wrapper => 'li', :wrapper_class => '', :selected_class => 'active', :url_segment => 1}
              = nav_link 'Donations', donations_path, { :class => 'link' }, {:wrapper => 'li', :wrapper_class => '', :selected_class => 'active', :url_segment => 1}
              = nav_link 'Donors', donors_path, { :class => 'link' }, {:wrapper => 'li', :wrapper_class => '', :selected_class => 'active', :url_segment => 1}
      .row
        #nav.clearfix
          - if notice
            %p#flash_notice= notice
          - if alert
            %p#flash_alert= alert
      = yield
      #copyright
        .container
          .row
            #rights.grid-6
              © 2013 All Rights Reserved.
            / /grid-6
            /
              <div id="totop" class="grid-6">
              <a href=""></a>
              </div>
            / /row
          / /container
        / /copyright
      / /wrapper
    %script{:src => "/js/focus.js"}
    :javascript
      $(function () {
        $('#masthead-carousel').carousel ({ interval: false });
      });